name: Test

on:
  # Run on pushes to select branches and on all pull requests.
  push:
    branches:
      - master
      - develop
      - 'release/[0-9]+.[0-9]+*'
      - 'hotfix/[0-9]+.[0-9]+*'
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - php_version: '5.6'
            wp_version: '5.6'
            multisite: true

          - php_version: '7.0'
            wp_version: '5.8'
            multisite: false

          - php_version: '7.2'
            wp_version: '5.6'
            multisite: false

          - php_version: '7.3'
            wp_version: 'trunk'
            multisite: true

          - php_version: '7.4'
            wp_version: '5.7'
            multisite: false

          # WP 5.6 is the earliest version which (sort of) supports PHP 8.0.
          - php_version: '8.0'
            wp_version: '5.8'
            multisite: false

          # WP 5.9 is the earliest version which (sort of) supports PHP 8.1.
          - php_version: '8.1'
            wp_version: 'trunk'
            multisite: true

    name: "Integration Test: PHP ${{ matrix.php_version }} | WP ${{ matrix.wp_version }} | multisite: ${{ matrix.multisite }}"

    # Allow builds to fail on as-of-yet unreleased PHP versions.
    continue-on-error: ${{ matrix.wp_version == 'trunk' }}

    services:
      mysql:
        # Use MySQL 5.7 for PHP < 7.4, otherwise MySQL 8.0.
        image: mysql:${{ ( matrix.php_version < 7.4 && '5.7' ) || '8.0' }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
          coverage: none

      # Determine the type of Composer install which is needed.
      # 1: WP 5.9 or higher - all PHPUnit versions needed are supported, use the most appropriate one.
      # 2. WP < 5.9 with PHP 8.0 or higher - PHPUnit 5 - 7 supported, locked at 5.x, but needs upgrade to 7 for PHP >= 8.0.
      # 3. WP < 5.9 with PHP < 8.0 - just use the locked PHPUnit 5 version.
      - name: Determine the type of Composer install to use
        id: composer_toggle
        run: |
          if [[ "${{ matrix.wp_version }}" =~ ^trunk|5\.9|[6789]\.[0-9]$ ]]; then
            echo '::set-output name=TYPE::1'
          elif [[ "${{ matrix.php_version }}" > "7.4" ]]; then
            echo '::set-output name=TYPE::2'
          else
            echo '::set-output name=TYPE::3'
          fi

      - name: Debug info - show type determined
        run: echo ${{ steps.composer_toggle.outputs.TYPE }}

      # Install dependencies and handle caching in one go.
      # Includes updating the test dependencies to the most appropriate version
      # for the PHP/WP version combination on which the tests will be run.
      # @link https://github.com/marketplace/actions/install-composer-dependencies

      ### Install type 1.
      - name: "Install type 1: remove the PHP platform requirement"
        if: ${{ steps.composer_toggle.outputs.TYPE == '1' }}
        run: composer config --unset platform.php

      - name: "Install type 1: install Composer dependencies - WP 5.9 or higher"
        if: ${{ steps.composer_toggle.outputs.TYPE == '1' }}
        uses: ramsey/composer-install@v1
        with:
          # Force a `composer update` run.
          dependency-versions: "highest"
          # But make it selective.
          composer-options: "yoast/wp-test-utils --with-dependencies"

      ### Install type 2.
      # Note: the steps for this type have (temporarily) been changed to get round
      # a Composer bug: https://github.com/composer/composer/issues/10394
      # Once that bug has been fixed, it is recommended to revert these steps to the
      # more optimized version which was previously in place.
      - name: "Install type 2: install Composer dependencies - WP < 5.9 with PHP >= 8.0"
        if: ${{ steps.composer_toggle.outputs.TYPE == '2' }}
        # This is just a plain install to still be able to use the cache for the most part.
        uses: ramsey/composer-install@v1

      - name: "Install type 2: remove wp-test-utils (temporary - Composer bug #10394)"
        if: ${{ steps.composer_toggle.outputs.TYPE == '2' }}
        run: composer remove --dev yoast/wp-test-utils --no-interaction

      - name: "Install type 2: reinstall wp-test-utils with specific PHPUnit version (temporary - Composer bug #10394)"
        if: ${{ steps.composer_toggle.outputs.TYPE == '2' }}
        run: composer require --dev yoast/wp-test-utils:"^1.0.0" phpunit/phpunit:"^7.5" --update-with-dependencies --ignore-platform-reqs --no-interaction

      ### Install type 3.
      - name: "Install type 3: install Composer dependencies - WP < 5.9 with PHP < 8.0"
        if: ${{ steps.composer_toggle.outputs.TYPE == '3' }}
        uses: ramsey/composer-install@v1

      - name: Install WP
        run: tests/bin/install-wp-tests.sh wordpress_tests root '' 127.0.0.1:3306 ${{ matrix.wp_version }}

      - name: Run unit tests - single site
        if: ${{ matrix.multisite == false }}
        run: composer test

      - name: Run unit tests - multisite
        if: ${{ matrix.multisite == true }}
        run: composer test
        env:
          WP_MULTISITE: 1
